id: IA1BA59B5
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T10:25:07.860690'
last_modified: '2022-06-19T10:25:07.860702'
parser: null
source_metadata:
  title: Hagiography of sGo rum pa Kun dga legs pai blo gros rgyal mtshan (1477–1544
    or 1489–1556); Lamdre Lobshe, vol. kha, title no. 4
  author: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་ཕྱུག
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-26);
    converted from external file, unrevised, spell-checked, notes implemented, thematic
    TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Kunga Dorje (kun)
  text_witnesses: https://sakyaresearch.org/sources/385
  bases:
    b017:
      title: Hagiography of sGo rum pa Kun dga legs pai blo gros rgyal mtshan (1477–1544
        or 1489–1556); Lamdre Lobshe, vol. kha, title no. 4
      order: 1
      base_file: b017.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
